seed: 42
device: cuda
amp: true
model:
  name: hitagu_net
  backbone: resnet50
  feature_dim: 1024
  hidden_dim: 512
  attn_dim: 512
  num_classes: 700
  drop: 0.5
data:
  dataset: K700
  root: /data/kinetics700
  train_list: train.csv
  val_list: val.csv
  frames_per_clip: 32
  frame_stride: 2
  img_size: 224
  mean: [0.485, 0.456, 0.406]
  std:  [0.229, 0.224, 0.225]
train:
  epochs: 100
  batch_size: 16
  optimizer: sgd
  lr: 0.01
  weight_decay: 1e-4
  momentum: 0.9
  nesterov: true
  warmup_epochs: 5
  clip_grad_norm: 5.0
  log_interval: 50
  checkpoint_dir: checkpoints
eval:
  single_clip: true
  single_crop: true
